import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.45.4'
const app=document.getElementById('app')
const cfg={url:window.CATS_SUPABASE_URL||'',key:window.CATS_SUPABASE_ANON_KEY||''}
const configured=cfg.url.startsWith('https://')&&cfg.url.includes('.supabase.co')&&cfg.key.length>40&&!cfg.url.includes('DEIN-PROJEKT')
const supabase=configured?createClient(cfg.url,cfg.key):null
const state={session:null,view:'home',cats:[],mating:null,pregnancy:null,tasks:[],weights:[],timeline:[]}
const plan=[{day:0,title:'Deckung dokumentieren',text:'Deckdatum, Deckkater, Anzahl Deckakte und Verhalten festhalten.'},{day:2,title:'Rolligkeit kontrollieren',text:'Prüfen, ob Rufen und Paarungsstellung abgeklungen sind.'},{day:7,title:'Gewicht erfassen',text:'Startgewicht dokumentieren und wöchentliche Kontrolle beginnen.'},{day:21,title:'Ultraschall planen',text:'Zwischen Tag 21 und 25 ist Ultraschall sinnvoll.'},{day:42,title:'Wurfzimmer vorbereiten',text:'Wurfbox, Waage, Tücher und Notfallnummern bereitlegen.'},{day:56,title:'Röntgen optional prüfen',text:'Mit Tierarzt besprechen, ob ein Röntgen sinnvoll ist.'},{day:60,title:'Endphase',text:'Mehrmals täglich beobachten.'},{day:63,title:'Geburtsterminfenster',text:'Ab jetzt jederzeit mit der Geburt rechnen.'}]
const today=()=>new Date().toISOString().slice(0,10)
const addDays=(iso,d)=>{let x=new Date(iso+'T12:00:00');x.setDate(x.getDate()+d);return x.toISOString().slice(0,10)}
const diffDays=(a,b)=>Math.floor((new Date(b+'T12:00:00')-new Date(a+'T12:00:00'))/86400000)
const pretty=iso=>new Date(iso+'T12:00:00').toLocaleDateString('de-CH',{day:'2-digit',month:'2-digit',year:'numeric'})
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
function shell(html){app.innerHTML=`<div class="brand"><div class="logo">689</div><div><h1>689 Cats</h1><p class="muted">Beta 0.2 · Pregnancy Center</p></div></div>${html}`}
function nav(){return `<nav class="nav"><button data-view="home">Home</button><button data-view="pregnancy">Trächtigkeit</button><button data-view="cats">Katzen</button><button data-view="zucht">Zucht</button><button data-view="more">Mehr</button></nav>`}
function bindNav(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()})}
function renderLogin(){shell(`<form id="loginForm" class="card login"><p class="kicker">Login</p><h2>Willkommen</h2><input id="email" type="email" placeholder="E-Mail" required/><button>Magic Link senden</button></form>`);document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const email=document.getElementById('email').value;const{error}=await supabase.auth.signInWithOtp({email});alert(error?error.message:'Magic Link wurde gesendet. Öffne ihn im selben Safari-Browser.')}}
function lilly(){return state.cats.find(c=>c.call_name==='Lillifee')||state.cats[0]}
function pregDay(){return state.pregnancy?Math.max(0,diffDays(state.pregnancy.start_date,today())):0}
function progress(){return Math.min(100,Math.max(0,Math.round((pregDay()/65)*100)))}
function curPlan(){const d=pregDay();return [...plan].reverse().find(x=>x.day<=d)||plan[0]}
function nextPlan(){const d=pregDay();return plan.find(x=>x.day>d)||plan[plan.length-1]}
function lastWeight(){const cat=lilly();return state.weights.filter(w=>w.cat_id===cat?.id).sort((a,b)=>String(b.log_date).localeCompare(String(a.log_date)))[0]}
function taskList(){const open=state.tasks.filter(x=>x.status==='open').slice(0,5);return `<section class="card"><p class="kicker">Offene Aufgaben</p>${open.length?open.map(x=>`<div class="row"><span>${esc(x.title)}<br><small class="muted">${x.due_date?pretty(x.due_date):''}</small></span><button class="secondary doneTask" data-id="${x.id}">Erledigt</button></div>`).join(''):'<p class="muted">Keine offenen Aufgaben.</p>'}</section>`}
function bindTasks(){document.querySelectorAll('.doneTask').forEach(b=>b.onclick=async()=>{await supabase.from('tasks').update({status:'done'}).eq('id',b.dataset.id);await loadData()})}
function renderHome(){const d=pregDay(),cur=curPlan(),next=nextPlan(),lw=lastWeight();shell(`<section class="card hero"><div><p class="kicker">Heute bei 689 Cats</p><h2>Lillifee · Tag ${d}</h2><p>${esc(cur.text)}</p><p class="muted">Nächster Meilenstein: ${esc(next.title)} · Tag ${next.day}</p></div><div class="ring" style="--p:${progress()}%"><div><strong>${d}</strong><span>Tag</span></div></div></section><section class="card"><p class="kicker">Fortschritt</p><div class="progressbar"><span style="width:${progress()}%"></span></div><p class="muted">${progress()} % · Geburtsterminfenster: ${state.pregnancy?pretty(state.pregnancy.expected_from)+' – '+pretty(state.pregnancy.expected_to):''}</p></section><section class="grid2"><div class="card"><p class="kicker">Letztes Gewicht</p><h2>${lw?.weight_kg?lw.weight_kg+' kg':'offen'}</h2><p class="muted">${lw?.log_date?pretty(lw.log_date):'Noch kein Gewicht erfasst.'}</p></div><div class="card"><p class="kicker">Heute</p><p>Gewicht, Verhalten, Appetit und Temperatur erfassen.</p><button data-view="pregnancy" class="secondary">Öffnen</button></div></section>${taskList()}${nav()}`);bindNav();bindTasks()}
function renderPregnancy(){const d=pregDay(),cat=lilly();const rows=state.weights.filter(w=>w.cat_id===cat?.id).slice(0,6);shell(`<section class="card hero"><div><p class="kicker">Pregnancy Center</p><h2>Lillifee · Tag ${d}</h2><p class="muted">Tägliche Erfassung für Gewicht, Temperatur, Appetit und Verhalten.</p></div><div class="ring" style="--p:${progress()}%"><div><strong>${progress()}</strong><span>%</span></div></div></section><section class="card"><p class="kicker">Heute erfassen</p><div class="grid2"><input id="weightKg" type="number" step="0.01" placeholder="Gewicht kg"/><input id="temp" type="number" step="0.1" placeholder="Temperatur °C"/></div><select id="appetite"><option>Appetit normal</option><option>frisst weniger</option><option>frisst deutlich mehr</option><option>kein Appetit</option></select><select id="behaviour"><option>Verhalten normal</option><option>verschmust</option><option>ruhiger</option><option>unruhig</option><option>auffällig</option></select><textarea id="note" placeholder="Notiz"></textarea><button id="savePreg">Tagesnotiz speichern</button></section><section class="card"><p class="kicker">Gewichtsverlauf</p>${rows.length?rows.map(w=>`<div class="row"><span>${pretty(w.log_date)}<br><small class="muted">${esc(w.notes||'')}</small></span><b>${w.weight_kg||'-'} kg</b></div>`).join(''):'<p class="muted">Noch keine Einträge.</p>'}</section><section class="card"><p class="kicker">Trächtigkeits-Timeline</p><div class="timeline">${plan.map(p=>`<div class="event"><b>Tag ${p.day}</b><br>${esc(p.title)}<br><small class="muted">${esc(p.text)}</small></div>`).join('')}</div></section>${nav()}`);bindNav();document.getElementById('savePreg').onclick=savePregDay}
async function savePregDay(){const cat=lilly();const w=document.getElementById('weightKg').value;const temp=document.getElementById('temp').value;const appetite=document.getElementById('appetite').value;const behaviour=document.getElementById('behaviour').value;const note=document.getElementById('note').value;const txt=[temp?`Temperatur: ${temp} °C`:null,appetite,behaviour,note].filter(Boolean).join('\\n');if(w){await supabase.from('weight_logs').insert({owner_id:state.session.user.id,cat_id:cat.id,pregnancy_id:state.pregnancy.id,log_date:today(),weight_kg:Number(w),notes:txt})}await supabase.from('timeline_events').insert({owner_id:state.session.user.id,cat_id:cat.id,event_date:today(),title:'Tagesnotiz Trächtigkeit',description:txt,category:'pregnancy'});await loadData();state.view='pregnancy';render()}
function renderCats(){shell(`<section class="card"><p class="kicker">Katzen</p>${state.cats.map(c=>`<div class="row"><span><b>${esc(c.call_name||c.name||c.official_name)}</b><br><small class="muted">${esc(c.role)} · ${esc(c.color||c.breed)}</small></span><span class="gold">🐾</span></div>`).join('')}</section>${nav()}`);bindNav()}
function renderZucht(){shell(`<section class="card"><p class="kicker">Verpaarung</p><h2>${esc(state.mating?.title||'Noch keine Verpaarung')}</h2><p>Deckdatum: ${state.mating?.mating_date?pretty(state.mating.mating_date):'-'}</p></section>${nav()}`);bindNav()}
function renderMore(){shell(`<section class="card ok"><p class="kicker">System</p><h2>Beta 0.2 läuft</h2><p class="muted">Pregnancy Center aktiv.</p><button id="logout" class="secondary">Logout</button></section>${nav()}`);bindNav();document.getElementById('logout').onclick=async()=>{await supabase.auth.signOut();state.session=null;renderLogin()}}
function render(){if(!configured)return shell('<section class="card warn"><h2>config.js prüfen</h2></section>');if(!state.session)return renderLogin();if(state.view==='pregnancy')return renderPregnancy();if(state.view==='cats')return renderCats();if(state.view==='zucht')return renderZucht();if(state.view==='more')return renderMore();return renderHome()}
async function seedIfNeeded(){const uid=state.session.user.id;const{data:ex,error:e0}=await supabase.from('cats').select('id').eq('owner_id',uid).limit(1);if(e0)throw e0;if(ex?.length)return;const{data:c}=await supabase.from('catteries').insert({owner_id:uid,name:'689 Cats',website:'https://www.689cats.ch'}).select().single();const{data:l}=await supabase.from('cats').insert({owner_id:uid,cattery_id:c.id,name:"Romida's Lillifee",official_name:"Romida's Lillifee",call_name:'Lillifee',sex:'female',role:'queen',breed:'Maine Coon',color:'Silver Shaded',birth_date:'2024-11-04'}).select().single();const{data:n}=await supabase.from('cats').insert({owner_id:uid,cattery_id:c.id,name:"Country Gulliver's Nectarine",official_name:"Country Gulliver's Nectarine",call_name:'Nectarine',sex:'male',role:'external',breed:'Maine Coon',color:'Red Silver Tabby'}).select().single();await supabase.from('cats').insert({owner_id:uid,cattery_id:c.id,name:'Bacari',official_name:'Bacari',call_name:'Bacari',sex:'male',role:'stud',breed:'Maine Coon'});const{data:m}=await supabase.from('matings').insert({owner_id:uid,cattery_id:c.id,queen_id:l.id,sire_id:n.id,title:'Lillifee × Nectarine',mating_date:'2026-06-28',status:'mated'}).select().single();const{data:p}=await supabase.from('pregnancies').insert({owner_id:uid,mating_id:m.id,start_date:'2026-06-28',status:'active'}).select().single();await supabase.from('tasks').insert(plan.map(x=>({owner_id:uid,pregnancy_id:p.id,title:x.title,description:x.text,due_date:addDays('2026-06-28',x.day),priority:x.day>=60?'high':'normal'})))}
async function loadData(){try{shell('<section class="card"><p class="kicker">Lädt</p><h2>Verbinde mit Supabase...</h2></section>');await seedIfNeeded();const uid=state.session.user.id;const [a,b,c,d,e,f]=await Promise.all([supabase.from('cats').select('*').eq('owner_id',uid).order('created_at'),supabase.from('matings').select('*').eq('owner_id',uid).order('mating_date',{ascending:false}).limit(1),supabase.from('pregnancies').select('*').eq('owner_id',uid).order('created_at',{ascending:false}).limit(1),supabase.from('tasks').select('*').eq('owner_id',uid).order('due_date'),supabase.from('weight_logs').select('*').eq('owner_id',uid).order('log_date',{ascending:false}),supabase.from('timeline_events').select('*').eq('owner_id',uid).order('event_date',{ascending:false})]);[a,b,c,d,e,f].forEach(r=>{if(r.error)throw r.error});state.cats=a.data||[];state.mating=b.data?.[0]||null;state.pregnancy=c.data?.[0]||null;state.tasks=d.data||[];state.weights=e.data||[];state.timeline=f.data||[];render()}catch(err){shell(`<section class="card warn"><p class="kicker">Fehlerdiagnose</p><h2>Supabase lädt nicht korrekt</h2><p>${esc(err.message)}</p></section>`)}}
async function init(){if(!configured)return render();const{data}=await supabase.auth.getSession();state.session=data.session;supabase.auth.onAuthStateChange((_e,s)=>{state.session=s;if(s)loadData();else render()});if(state.session)await loadData();else render()}
init()
